---
name: Task - Run Cargo tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test-rust:
    runs-on: MSL-MADARA
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup the environment with all necessary dependencies
      - uses: ./.github/actions/load-env

      - name: Setup Rust Environment
        uses: ./.github/actions/rust-setup
        with:
          cache-key: ${{ env.BUILD_RUST_CACHE_KEY }}
          rust-version: ${{ env.BUILD_RUST_VERSION }}
          scarb-version: ${{ env.BUILD_SCARB_VERSION }}
          install-mold: true
          install-scarb: true
          install-foundry: true
          foundry-version: ${{ env.BUILD_FOUNDRY_VERSION }}

      - name: Run unit tests
        run: |
          cargo test --release --workspace
        env:
          PROPTEST_CASES: 2
