---
name: Task - Code Style Linting

# This workflow runs code style linters for non-Rust code
# including Prettier, Markdown, and TOML formatting checks
on:
  workflow_dispatch:
  workflow_call:

env:
  MARKDOWN_CONFIG: "./.markdownlint.json"
  TAPLO_VERSION: "0.9.3"
  TAPLO_CONFIG: "./taplo/taplo.toml"

jobs:
  # Run prettier for code formatting
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run prettier
        run: npx prettier --check .

  # Check markdown files for style consistency
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint root markdown
        uses: avto-dev/markdown-lint@v1
        with:
          config: ${{ env.MARKDOWN_CONFIG }}
          args: "."
          ignore: "./target"

  # Check TOML files for formatting
  toml-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Download taplo
        run: |
          curl -L https://github.com/tamasfe/taplo/releases/download/${{ env.TAPLO_VERSION }}/taplo-linux-x86_64.gz -o taplo.gz
          gunzip taplo.gz
          chmod +x taplo
          mv taplo /usr/local/bin/taplo

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check root toml files
        run: taplo fmt --config ${{ env.TAPLO_CONFIG }} --check

      - name: Check orchestrator toml files
        working-directory: orchestrator
        run: taplo fmt --config ../${{ env.TAPLO_CONFIG }} --check
