name: Task - Build Madara

# This workflow builds the main Madara binary and related components
# It also caches the build artifacts for other workflows to use
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      rust-version:
        description: 'Rust toolchain version to use'
        required: true
        type: string
      scarb-version:
        description: 'Scarb version to use'
        required: true
        type: string
      cache-prefix:
        description: 'Prefix for cache keys'
        required: false
        type: string
        default: 'madara'
    outputs:
      binary-hash:
        description: 'Hash of the built binary'
        value: ${{ jobs.build.outputs.binary-hash }}
      cairo-hash:
        description: 'Hash of Cairo artifacts'
        value: ${{ jobs.build.outputs.cairo-hash }}



jobs:
  build-madara:
    name: Build Madara
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      binary-hash: ${{ steps.generate_binary_hash.outputs.hash }}
      cairo-hash: ${{ steps.generate_cairo_hash.outputs.hash }}

    steps:
      # Setup the environment with all necessary dependencies
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Setup Rust Environment
        uses: ./.github/actions/rust-setup
        with:
          rust-version: ${{ inputs.rust-version }}
          scarb-version: ${{ inputs.scarb-version }}
          install-mold: true
          install-scarb: true
          install-foundry: true

      # Build Madara and test contracts
      - name: Build Madara and test contracts
        run: |
          export GIT_COMMIT_HASH=$GITHUB_SHA
          cargo build --release --bin madara
          cargo build --release -p m-cairo-test-contracts

      # Generate hash for the Madara binary
      - name: Generate binary hash
        id: generate_binary_hash
        run: |
          # Path to the compiled Madara binary
          BINARY_PATH=./target/release/madara
          # Get current Unix timestamp for uniqueness
          TIMESTAMP=$(date +%s)
          # Create hash by combining timestamp and binary content
          HASH=$(echo "$TIMESTAMP" | cat - $BINARY_PATH | sha256sum | awk '{ print $1 }')
          # Set output for use in subsequent steps
          echo "hash=$HASH" >> $GITHUB_OUTPUT
          # Save hash to file for artifact sharing
          echo "$HASH" > binary_hash.txt
          echo "Hash of the binary is: $HASH (with timestamp: $TIMESTAMP)"

      - name: Upload binary hash as artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-hash
          path: binary_hash.txt
          retention-days: 1

      - name: Cache Madara binary
        uses: actions/cache@v3
        with:
          path: target/release/madara
          key: ${{ runner.os }}-${{ inputs.cache-prefix }}-bin-${{ steps.generate_binary_hash.outputs.hash }}

      # Generate hash for Cairo artifacts
      - name: Generate Cairo artifacts hash
        id: generate_cairo_hash
        run: |
          # Get current Unix timestamp for uniqueness
          TIMESTAMP=$(date +%s)
          # Generate hash of all files in cairo/target directory
          FILES_HASH=$(find cairo/target -type f -exec sha256sum {} \; | sort | sha256sum | awk '{ print $1 }')
          # Combine timestamp with files hash for unique identifier
          HASH=$(echo "$TIMESTAMP $FILES_HASH" | sha256sum | awk '{ print $1 }')
          # Set output for use in subsequent steps
          echo "hash=$HASH" >> $GITHUB_OUTPUT
          # Save hash to file for artifact sharing
          echo "$HASH" > cairo_artifacts_hash.txt
          echo "Hash of Cairo artifacts is: $HASH (with timestamp: $TIMESTAMP)"

      - name: Upload Cairo artifacts hash
        uses: actions/upload-artifact@v4
        with:
          name: cairo-artifacts-hash
          path: cairo_artifacts_hash.txt
          retention-days: 1

      - name: Cache Cairo build artifacts
        uses: actions/cache@v3
        with:
          path: cairo/target
          key: ${{ runner.os }}-${{ inputs.cache-prefix }}-cairo-${{ steps.generate_cairo_hash.outputs.hash }} 