---
name: Task - Run Cargo tests

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      rust-version:
        description: "Rust toolchain version to use"
        required: true
        type: string
      scarb-version:
        description: "Scarb version to use"
        required: true
        type: string
      foundry-version:
        description: "Foundry version to use"
        required: true
        type: string

jobs:
  test-rust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust Environment
        uses: ./.github/actions/rust-setup
        with:
          rust-version: ${{ env.BUILD_RUST_VERSION }}
          scarb-version: ${{ env.BUILD_SCARB_VERSION }}
          install-mold: true
          install-scarb: true
          install-foundry: true
          foundry-version: ${{ env.BUILD_FOUNDRY_VERSION }}

      - name: Run unit tests
        run: |
          cargo test --release --workspace
        env:
          PROPTEST_CASES: 2
